//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerMsg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Group {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Group() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.ControllerMsg.Group.Group", typeof(Group).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad pagination parameters.
        /// </summary>
        public static string BadPaginationParams {
            get {
                return ResourceManager.GetString("BadPaginationParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch! We cannot find this channel....
        /// </summary>
        public static string CantFindChannel {
            get {
                return ResourceManager.GetString("CantFindChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch! We cannot find this group....
        /// </summary>
        public static string CantFindGroup {
            get {
                return ResourceManager.GetString("CantFindGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while retrieving info on your membership... Please, retry in a while!.
        /// </summary>
        public static string CantFindGroupOrUser {
            get {
                return ResourceManager.GetString("CantFindGroupOrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while joining the group. Please, retry in a while!.
        /// </summary>
        public static string CantJoinGroup {
            get {
                return ResourceManager.GetString("CantJoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving new nickname.
        /// </summary>
        public static string ChangeGroupInfoCantSaveNickname {
            get {
                return ResourceManager.GetString("ChangeGroupInfoCantSaveNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving new profile.
        /// </summary>
        public static string ChangeGroupInfoCantSaveProfile {
            get {
                return ResourceManager.GetString("ChangeGroupInfoCantSaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehi, this name is already used by another group or channel!.
        /// </summary>
        public static string ChangeGroupInfoNickNameAlreadyPresent {
            get {
                return ResourceManager.GetString("ChangeGroupInfoNickNameAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! New info has been successfully saved!.
        /// </summary>
        public static string ChangeGroupInfoSaveSuccess {
            get {
                return ResourceManager.GetString("ChangeGroupInfoSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is taken, try.
        /// </summary>
        public static string ChangeGroupInfoSuggestions {
            get {
                return ResourceManager.GetString("ChangeGroupInfoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving your picture.
        /// </summary>
        public static string ChangePictureCantSavePicture {
            get {
                return ResourceManager.GetString("ChangePictureCantSavePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh, seems that no picture has been selected!.
        /// </summary>
        public static string ChangePictureNoPicture {
            get {
                return ResourceManager.GetString("ChangePictureNoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! Picture has been successfully saved!.
        /// </summary>
        public static string ChangePictureSaveSuccess {
            get {
                return ResourceManager.GetString("ChangePictureSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, an error occurred while creating your channel... Please, try again!.
        /// </summary>
        public static string CreateChannelGenericError {
            get {
                return ResourceManager.GetString("CreateChannelGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This topic is too long: max 128 chars!.
        /// </summary>
        public static string CreateChannelInvalidTopic {
            get {
                return ResourceManager.GetString("CreateChannelInvalidTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! New channel has been successfully created!.
        /// </summary>
        public static string CreateChannelSuccess {
            get {
                return ResourceManager.GetString("CreateChannelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, an error occurred while creating your group... Please, try again!.
        /// </summary>
        public static string CreateGroupGenericError {
            get {
                return ResourceManager.GetString("CreateGroupGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is not valid: 3 to 50 chars without special chars!.
        /// </summary>
        public static string CreateGroupInvalidName {
            get {
                return ResourceManager.GetString("CreateGroupInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This topic is too long: max 128 chars!.
        /// </summary>
        public static string CreateGroupInvalidShortDescr {
            get {
                return ResourceManager.GetString("CreateGroupInvalidShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! New group has been successfully created!.
        /// </summary>
        public static string CreateGroupSuccess {
            get {
                return ResourceManager.GetString("CreateGroupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, an error occurred while deleting your channel... Please, try again!.
        /// </summary>
        public static string DeleteChannelGenericError {
            get {
                return ResourceManager.GetString("DeleteChannelGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK! The channel has been successfully deleted!.
        /// </summary>
        public static string DeleteChannelSuccess {
            get {
                return ResourceManager.GetString("DeleteChannelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, an error occurred while deleting your group... Please, try again!.
        /// </summary>
        public static string DeleteGroupGenericError {
            get {
                return ResourceManager.GetString("DeleteGroupGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK! The group has been successfully deleted!.
        /// </summary>
        public static string DeleteGroupSuccess {
            get {
                return ResourceManager.GetString("DeleteGroupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, give a name to your group!.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, no: you are not an administrator of this group!.
        /// </summary>
        public static string UserNotAdmin {
            get {
                return ResourceManager.GetString("UserNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, no: you are not an administrator of this channel!.
        /// </summary>
        public static string UserNotAdminForChannel {
            get {
                return ResourceManager.GetString("UserNotAdminForChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: user is not allowed to see this group {0}.
        /// </summary>
        public static string UserNotAllowedToSeeError {
            get {
                return ResourceManager.GetString("UserNotAllowedToSeeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: user is not allowed to see the channel {0}.
        /// </summary>
        public static string UserNotAllowedToSeeErrorForChannel {
            get {
                return ResourceManager.GetString("UserNotAllowedToSeeErrorForChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What?? Seems you are not logged in.
        /// </summary>
        public static string UserNotLogged {
            get {
                return ResourceManager.GetString("UserNotLogged", resourceCulture);
            }
        }
    }
}
