//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Faq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Faq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.WebPages.Faq.Faq", typeof(Faq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A snippet is defined at least by a title, the code content and the visibility. .
        /// </summary>
        public static string BasicFieldsA {
            get {
                return ResourceManager.GetString("BasicFieldsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which are the very basic fields of a snippet?.
        /// </summary>
        public static string BasicFieldsQ {
            get {
                return ResourceManager.GetString("BasicFieldsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Channel is a repository of public snippets linked together by a common topic. A user may follow a channel in order to be notified on the latest news about that stuff. Everyone may create and administer a channel, maybe providing some special introduction as a description of the channel and related topic. This is the ideal place to gather the highest visibility for you coolest snippets!.
        /// </summary>
        public static string ChannelsA {
            get {
                return ResourceManager.GetString("ChannelsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a Channel?.
        /// </summary>
        public static string ChannelsQ {
            get {
                return ResourceManager.GetString("ChannelsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Group is a set of users that can share some snippets just only among them. A snippet shared with a group is visible only by the belongers of this group. The users that join a the group can be administrators or simple belongers. The snippets shared in the group can be edited only by the administrators and by the creator of the snippet itself, while simple belongers may only view and comment. In this way, the real aim of the group is to preserve the knowledge of a team, without leaving strangers to put the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GroupsA {
            get {
                return ResourceManager.GetString("GroupsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a Group?.
        /// </summary>
        public static string GroupsQ {
            get {
                return ResourceManager.GetString("GroupsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a software guru? Make the world a better place by posting your coolest snippets! First of all, publish your snippets on one or more channels: from the Snippet View page, press the &quot;PUBLISH&quot; button and select one or more channels where your snippet may be seen by tons of other guys. Then, you may achieve further visibility by posting your cool stuff onto the social networks like Facebook, Twitter and LinkedIn: from the Snippet View Page, press one of the buttons near &quot;Snippet Posting Options&quot; and pre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PublishA {
            get {
                return ResourceManager.GetString("PublishA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How may I make the world aware of my software knowledge?.
        /// </summary>
        public static string PublishQ {
            get {
                return ResourceManager.GetString("PublishQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip2Code search works with a pattern matching technique with respect to the tags, a full-text search with respect to the description of the snippet, and applies a proprietary algorithm for the properties.
        ///Given this scenario, the best way to decorate a snippet is to write a good description, just like the comments written on top of classes or public methods. Moreover, Snip2Code automatically detects some properties and tags from the content and the title of the snippet, but no automatic discovery may repl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SearchabilityA {
            get {
                return ResourceManager.GetString("SearchabilityA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How may I make my snippet easier to be retrieved?.
        /// </summary>
        public static string SearchabilityQ {
            get {
                return ResourceManager.GetString("SearchabilityQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may share your snippets with a group of friends and/or colleagues from the Snippet View page: here, press the &quot;SHARE&quot; button and select one of your groups. If you don&apos;t have any group, you may create your own, and invite your friends to join it! In this way, only you and your group members will be able to see the shared snippets..
        /// </summary>
        public static string ShareA {
            get {
                return ResourceManager.GetString("ShareA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How may I share my snippets with my friends and colleagues?.
        /// </summary>
        public static string ShareQ {
            get {
                return ResourceManager.GetString("ShareQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A snippet is a chunk of code, usually self-contained, that solves a particular task. It can vary from a simple line of code (e.g. a batch command, a regex, etc.) to hundreds of lines (e.g. cryptographic algorithms...). It can also be a mix of several languages (e.g. HTML tags + CSS styles + javascript). The only  limit is your fantasy!.
        /// </summary>
        public static string SnippetA {
            get {
                return ResourceManager.GetString("SnippetA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a snippet?.
        /// </summary>
        public static string SnippetQ {
            get {
                return ResourceManager.GetString("SnippetQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags are simple attributes of snippets, used to search them for an exact match (or &apos;LIKE&apos; behavior with jolly characters). Properties add scope to the features of the snippets, and the capability to search with &apos;&gt;&apos; and &apos;&lt;&apos; operators. In this way, a snippet with a property like &quot;Windows Version = WindowsXP&quot; will match the search &quot;Windows Version &lt; Windows7&quot;. You can also create your own properties, to expand the management capabilities of your basket of snippets! .
        /// </summary>
        public static string TagsVSPropsA {
            get {
                return ResourceManager.GetString("TagsVSPropsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the difference between tags and properties?.
        /// </summary>
        public static string TagsVSPropsQ {
            get {
                return ResourceManager.GetString("TagsVSPropsQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visibility field determines who can see your snippet. 
        ///There are 3 classes of visibility: &quot;Only me&quot; makes the snippet private for the creator, and nobody else will have access to it. &quot;Everyone&quot; exposes the snippet to the outside world, so that everybody on the Internet will be able to see it. Otherwise, you will be able to share the snippet with one of your groups; in this case, only the belongers of this group will be able to access it (and only the group administrators will be able to edit it, togeth [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VisibilityA {
            get {
                return ResourceManager.GetString("VisibilityA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How may I cope with Visibility field?.
        /// </summary>
        public static string VisibilityQ {
            get {
                return ResourceManager.GetString("VisibilityQ", resourceCulture);
            }
        }
    }
}
