//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2CModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchEngine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchEngine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.S2CModels.SearchEngine.SearchEngine", typeof(SearchEngine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Metadata parameters list.
        /// </summary>
        public static string emptyMetaList {
            get {
                return ResourceManager.GetString("emptyMetaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error number: {0} - {1}.
        /// </summary>
        public static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string bad formatted.
        /// </summary>
        public static string inputBadFormat {
            get {
                return ResourceManager.GetString("inputBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search Engine failed: could not clean up results of search.
        /// </summary>
        public static string noCleanUp {
            get {
                return ResourceManager.GetString("noCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search Engine failed: cannot find user total set of items.
        /// </summary>
        public static string noContext {
            get {
                return ResourceManager.GetString("noContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve creator ID information.
        /// </summary>
        public static string noCreatorIDInfo {
            get {
                return ResourceManager.GetString("noCreatorIDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Errors Found!!!.
        /// </summary>
        public static string noErrors {
            get {
                return ResourceManager.GetString("noErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search Engine failed: could not extract results of search.
        /// </summary>
        public static string noExtraction {
            get {
                return ResourceManager.GetString("noExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search Engine failed: could not limit results of search.
        /// </summary>
        public static string noLimitResult {
            get {
                return ResourceManager.GetString("noLimitResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve owner group ID information.
        /// </summary>
        public static string noOwnerGroupIDInfo {
            get {
                return ResourceManager.GetString("noOwnerGroupIDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve rating information.
        /// </summary>
        public static string noRatingInfo {
            get {
                return ResourceManager.GetString("noRatingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search Engine failed: could not retrieve results of search.
        /// </summary>
        public static string noResult {
            get {
                return ResourceManager.GetString("noResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search Engine failed: could not sort results of search.
        /// </summary>
        public static string noSortedResult {
            get {
                return ResourceManager.GetString("noSortedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse more than one parameter.
        /// </summary>
        public static string parse1moreParam {
            get {
                return ResourceManager.GetString("parse1moreParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse more than two parameters.
        /// </summary>
        public static string parse2moreParam {
            get {
                return ResourceManager.GetString("parse2moreParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse &apos;Count&apos; Attribute.
        /// </summary>
        public static string parseCount {
            get {
                return ResourceManager.GetString("parseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing search expression.
        /// </summary>
        public static string parsingError {
            get {
                return ResourceManager.GetString("parsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search Engine failed: undefined data flow.
        /// </summary>
        public static string undefDataFlow {
            get {
                return ResourceManager.GetString("undefDataFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined Error.
        /// </summary>
        public static string undefined {
            get {
                return ResourceManager.GetString("undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined symbol while compiling search expression.
        /// </summary>
        public static string undefSymbol {
            get {
                return ResourceManager.GetString("undefSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search Engine failed: Unknown operator.
        /// </summary>
        public static string unknownOp {
            get {
                return ResourceManager.GetString("unknownOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched braces.
        /// </summary>
        public static string unmatchedBraces {
            get {
                return ResourceManager.GetString("unmatchedBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unparsable Search Expression.
        /// </summary>
        public static string unparsableExpr {
            get {
                return ResourceManager.GetString("unparsableExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecoverable Parsing error.
        /// </summary>
        public static string unRecoverableParsing {
            get {
                return ResourceManager.GetString("unRecoverableParsing", resourceCulture);
            }
        }
    }
}
