//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerMsg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.ControllerMsg.User.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while backupping your snippets.
        /// </summary>
        public static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving new email address.
        /// </summary>
        public static string ChangeEmailCantSaveEmail {
            get {
                return ResourceManager.GetString("ChangeEmailCantSaveEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: password is too short! At least 4 chars without spaces....
        /// </summary>
        public static string ChangeEmailEmptyPsw {
            get {
                return ResourceManager.GetString("ChangeEmailEmptyPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the email: it seems invalid!.
        /// </summary>
        public static string ChangeEmailInvalidEmail {
            get {
                return ResourceManager.GetString("ChangeEmailInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! New email address has been saved!.
        /// </summary>
        public static string ChangeEmailSaveSuccess {
            get {
                return ResourceManager.GetString("ChangeEmailSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: wrong password.
        /// </summary>
        public static string ChangeEmailWrongPsw {
            get {
                return ResourceManager.GetString("ChangeEmailWrongPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving your picture.
        /// </summary>
        public static string ChangePictureCantSavePicture {
            get {
                return ResourceManager.GetString("ChangePictureCantSavePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh, seems that no picture has been selected!.
        /// </summary>
        public static string ChangePictureNoPicture {
            get {
                return ResourceManager.GetString("ChangePictureNoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! Picture has been successfully saved!.
        /// </summary>
        public static string ChangePictureSaveSuccess {
            get {
                return ResourceManager.GetString("ChangePictureSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh, seems that the email you entered is invalid!.
        /// </summary>
        public static string ChangePictureWrongGravatarEmail {
            get {
                return ResourceManager.GetString("ChangePictureWrongGravatarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh, seems that your picture is not suited for us: please, specify a PNG, JPG or BMP file, with a size smaller than 2MB.
        /// </summary>
        public static string ChangePictureWrongPicture {
            get {
                return ResourceManager.GetString("ChangePictureWrongPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving new password.
        /// </summary>
        public static string ChangePswCantSavePsw {
            get {
                return ResourceManager.GetString("ChangePswCantSavePsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! Password has been successfully saved!.
        /// </summary>
        public static string ChangePswSaveSuccess {
            get {
                return ResourceManager.GetString("ChangePswSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: password is too short! At least 4 chars without spaces....
        /// </summary>
        public static string ChangePswWrongLenght {
            get {
                return ResourceManager.GetString("ChangePswWrongLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: wrong password.
        /// </summary>
        public static string ChangePswWrongPsw {
            get {
                return ResourceManager.GetString("ChangePswWrongPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: the passwords don&apos;t match.
        /// </summary>
        public static string ChangePswWrongRepeat {
            get {
                return ResourceManager.GetString("ChangePswWrongRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving Twitter username.
        /// </summary>
        public static string ChangeTwitterNicknameCantSaveUsername {
            get {
                return ResourceManager.GetString("ChangeTwitterNicknameCantSaveUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehi, seems that Twitter username is empty! Don&apos;t you want to be cited in all the tweets regarding your snippets?.
        /// </summary>
        public static string ChangeTwitterNickNameEmpty {
            get {
                return ResourceManager.GetString("ChangeTwitterNickNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! Your Twitter username has been successfully saved!.
        /// </summary>
        public static string ChangeTwitterNicknameSaveSuccess {
            get {
                return ResourceManager.GetString("ChangeTwitterNicknameSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while setting notification settings. Please, retry in a while..
        /// </summary>
        public static string ChangeUserAlertError {
            get {
                return ResourceManager.GetString("ChangeUserAlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehi, seems that some preferences have not been set. Set them all, please! .
        /// </summary>
        public static string ChangeUserAlertsEmptyPrefs {
            get {
                return ResourceManager.GetString("ChangeUserAlertsEmptyPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! New preferences have been successfully saved!.
        /// </summary>
        public static string ChangeUserAlertSuccess {
            get {
                return ResourceManager.GetString("ChangeUserAlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving new profile.
        /// </summary>
        public static string ChangeUserInfoCantSaveProfile {
            get {
                return ResourceManager.GetString("ChangeUserInfoCantSaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while saving new username.
        /// </summary>
        public static string ChangeUserInfoCantSaveUsername {
            get {
                return ResourceManager.GetString("ChangeUserInfoCantSaveUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehi, this email is already used by another guy!.
        /// </summary>
        public static string ChangeUserInfoEmailAlreadyPresent {
            get {
                return ResourceManager.GetString("ChangeUserInfoEmailAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the first name: it seems invalid!.
        /// </summary>
        public static string ChangeUserInfoInvalidFirstName {
            get {
                return ResourceManager.GetString("ChangeUserInfoInvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the last name: it seems invalid!.
        /// </summary>
        public static string ChangeUserInfoInvalidLastName {
            get {
                return ResourceManager.GetString("ChangeUserInfoInvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the username: it seems invalid!.
        /// </summary>
        public static string ChangeUserInfoInvalidNickname {
            get {
                return ResourceManager.GetString("ChangeUserInfoInvalidNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehi, this nickname is already used by another guy!.
        /// </summary>
        public static string ChangeUserInfoNickNameAlreadyPresent {
            get {
                return ResourceManager.GetString("ChangeUserInfoNickNameAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehi, seems that nickname is empty! Don&apos;t you want to have the coolest username of the neighborhood?.
        /// </summary>
        public static string ChangeUserInfoNickNameEmpty {
            get {
                return ResourceManager.GetString("ChangeUserInfoNickNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! New profile has been successfully saved!.
        /// </summary>
        public static string ChangeUserInfoSaveSuccess {
            get {
                return ResourceManager.GetString("ChangeUserInfoSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is taken, try.
        /// </summary>
        public static string ChangeUserInfoSuggestions {
            get {
                return ResourceManager.GetString("ChangeUserInfoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ehi, you haven&apos;t got access to this group!.
        /// </summary>
        public static string ChangeUserInfoWrongDefaultGroup {
            get {
                return ResourceManager.GetString("ChangeUserInfoWrongDefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while checking your GitHub account. Please, retry in a while..
        /// </summary>
        public static string ImportGithubError {
            get {
                return ResourceManager.GetString("ImportGithubError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! Your GitHub profile has been merged with the Snip2Code one!.
        /// </summary>
        public static string ImportGithubSaveSuccess {
            get {
                return ResourceManager.GetString("ImportGithubSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No snippets have been imported. Please check the submitted file..
        /// </summary>
        public static string ImportSnippetNoSavedMsg {
            get {
                return ResourceManager.GetString("ImportSnippetNoSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 snippet has been correctly imported!.
        /// </summary>
        public static string ImportSnippetOKMsg {
            get {
                return ResourceManager.GetString("ImportSnippetOKMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh, seems that no file has been selected!.
        /// </summary>
        public static string ImportSnippetsNoFile {
            get {
                return ResourceManager.GetString("ImportSnippetsNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} snippets have been correctly imported!.
        /// </summary>
        public static string ImportSnippetsOKMsg {
            get {
                return ResourceManager.GetString("ImportSnippetsOKMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong while checking your Stackoverflow account. Please, retry in a while..
        /// </summary>
        public static string ImportStackoverflowError {
            get {
                return ResourceManager.GetString("ImportStackoverflowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent! Your Stackoverflow profile has been merged with the Snip2Code one!.
        /// </summary>
        public static string ImportStackoverflowSaveSuccess {
            get {
                return ResourceManager.GetString("ImportStackoverflowSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: user is not allowed to see this user {0}.
        /// </summary>
        public static string UserNotAllowedToSeeError {
            get {
                return ResourceManager.GetString("UserNotAllowedToSeeError", resourceCulture);
            }
        }
    }
}
