//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerMsg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Snippets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Snippets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.ControllerMsg.Snippets.Snippets", typeof(Snippets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! This comment cannot be added to the snippet {0}.
        /// </summary>
        public static string AddCommentCantAddComment {
            get {
                return ResourceManager.GetString("AddCommentCantAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the comment cannot be added!.
        /// </summary>
        public static string AddCommentNegSnippetError {
            get {
                return ResourceManager.GetString("AddCommentNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... empty comment: nothing to add!.
        /// </summary>
        public static string AddCommentNullError {
            get {
                return ResourceManager.GetString("AddCommentNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! This property ({1}:{2}) cannot be added to the snippet {0}.
        /// </summary>
        public static string AddPropCantAddProp {
            get {
                return ResourceManager.GetString("AddPropCantAddProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the property cannot be added!.
        /// </summary>
        public static string AddPropNegSnippetError {
            get {
                return ResourceManager.GetString("AddPropNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: we can&apos;t add a property without name.
        /// </summary>
        public static string AddPropNoNameError {
            get {
                return ResourceManager.GetString("AddPropNoNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: we can&apos;t add a property without value.
        /// </summary>
        public static string AddPropNoValueError {
            get {
                return ResourceManager.GetString("AddPropNoValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! These properties cannot be added to the snippet {0}.
        /// </summary>
        public static string AddPropsFromWebCantAddProps {
            get {
                return ResourceManager.GetString("AddPropsFromWebCantAddProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the properties cannot be added!.
        /// </summary>
        public static string AddPropsFromWebNegSnippetError {
            get {
                return ResourceManager.GetString("AddPropsFromWebNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... empty list of properties: nothing to add!.
        /// </summary>
        public static string AddPropsFromWebNullPropsError {
            get {
                return ResourceManager.GetString("AddPropsFromWebNullPropsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!! Something wrong during the vote of the snippet {0}.
        /// </summary>
        public static string AddRateCantAddRate {
            get {
                return ResourceManager.GetString("AddRateCantAddRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: cannot give a negative vote!.
        /// </summary>
        public static string AddRateNegativeError {
            get {
                return ResourceManager.GetString("AddRateNegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the vote cannot be added!.
        /// </summary>
        public static string AddRateNegSnippetError {
            get {
                return ResourceManager.GetString("AddRateNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!! Something wrong reading incoming Snippet.
        /// </summary>
        public static string AddSnippetError {
            get {
                return ResourceManager.GetString("AddSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! These tags cannot be added to the snippet {0}.
        /// </summary>
        public static string AddTagsFromWebCantAddTags {
            get {
                return ResourceManager.GetString("AddTagsFromWebCantAddTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the tags cannot be added!.
        /// </summary>
        public static string AddTagsFromWebNegSnippetError {
            get {
                return ResourceManager.GetString("AddTagsFromWebNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... empty list of tags: nothing to add!.
        /// </summary>
        public static string AddTagsFromWebNullTagsError {
            get {
                return ResourceManager.GetString("AddTagsFromWebNullTagsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! There&apos;s no clue of this snippet!.
        /// </summary>
        public static string CantFindSnippetError {
            get {
                return ResourceManager.GetString("CantFindSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! The properties cannot be cleared from the snippet {0}.
        /// </summary>
        public static string ClearPropertiesError {
            get {
                return ResourceManager.GetString("ClearPropertiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the properties cannot be cleared!.
        /// </summary>
        public static string ClearPropertiesNegSnippetError {
            get {
                return ResourceManager.GetString("ClearPropertiesNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! The tags cannot be cleared from the snippet {0}.
        /// </summary>
        public static string ClearTagsError {
            get {
                return ResourceManager.GetString("ClearTagsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the tags cannot be cleared!.
        /// </summary>
        public static string ClearTagsNegSnippetError {
            get {
                return ResourceManager.GetString("ClearTagsNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!! Something wrong while counting the snippet of group {0}.
        /// </summary>
        public static string CountSnippetError {
            get {
                return ResourceManager.GetString("CountSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: cannot see the contents of this group!.
        /// </summary>
        public static string CountSnippetWrongGroup {
            get {
                return ResourceManager.GetString("CountSnippetWrongGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! There&apos;s no clue of this snippet!.
        /// </summary>
        public static string DeleteCommentCantFindSnippetError {
            get {
                return ResourceManager.GetString("DeleteCommentCantFindSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! This comment ({0}) cannot be removed.
        /// </summary>
        public static string DeleteCommentError {
            get {
                return ResourceManager.GetString("DeleteCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: cannot remove a negative comment ({0})!.
        /// </summary>
        public static string DeleteCommentNegCommentError {
            get {
                return ResourceManager.GetString("DeleteCommentNegCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: cannot remove a property without a name!.
        /// </summary>
        public static string DeletePropEmptyNameError {
            get {
                return ResourceManager.GetString("DeletePropEmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: cannot remove a property without a value!.
        /// </summary>
        public static string DeletePropEmptyValueError {
            get {
                return ResourceManager.GetString("DeletePropEmptyValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!! Something wrong while removing the property {0} from the snippet {1}.
        /// </summary>
        public static string DeletePropError {
            get {
                return ResourceManager.GetString("DeletePropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: cannot remove a negative property ({0})!.
        /// </summary>
        public static string DeletePropNegPropError {
            get {
                return ResourceManager.GetString("DeletePropNegPropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the property cannot be removed!.
        /// </summary>
        public static string DeletePropNegSnippetError {
            get {
                return ResourceManager.GetString("DeletePropNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!! Something wrong while removing the snippet {0}.
        /// </summary>
        public static string DeleteSnippetError {
            get {
                return ResourceManager.GetString("DeleteSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): it cannot be removed!.
        /// </summary>
        public static string DeleteSnippetNegSnippetError {
            get {
                return ResourceManager.GetString("DeleteSnippetNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!! Something wrong while removing these tags from the snippet {0}.
        /// </summary>
        public static string DeleteTagsError {
            get {
                return ResourceManager.GetString("DeleteTagsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): the tags cannot be deleted!.
        /// </summary>
        public static string DeleteTagsNegSnippetError {
            get {
                return ResourceManager.GetString("DeleteTagsNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! There&apos;s no content here....
        /// </summary>
        public static string FindGroupItemsError {
            get {
                return ResourceManager.GetString("FindGroupItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! There&apos;s no content here...
        /// </summary>
        public static string FindItemsError {
            get {
                return ResourceManager.GetString("FindItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! There&apos;s no clue of this comment!.
        /// </summary>
        public static string GetCommentError {
            get {
                return ResourceManager.GetString("GetCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}).
        /// </summary>
        public static string NegSnippetError {
            get {
                return ResourceManager.GetString("NegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! Cannot parse incoming input: input is null.
        /// </summary>
        public static string NullInput {
            get {
                return ResourceManager.GetString("NullInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! Cannot parse incoming input:.
        /// </summary>
        public static string ParseInputError {
            get {
                return ResourceManager.GetString("ParseInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!! Something wrong while publishing the snippet {0}.
        /// </summary>
        public static string PublishCantPublish {
            get {
                return ResourceManager.GetString("PublishCantPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): it can&apos;t be published!.
        /// </summary>
        public static string PublishNegSnippetError {
            get {
                return ResourceManager.GetString("PublishNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: cannot publish to an empty list of channels!.
        /// </summary>
        public static string PublishWrongChannel {
            get {
                return ResourceManager.GetString("PublishWrongChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!! Something wrong while sharing the snippet {0}.
        /// </summary>
        public static string ShareCantShare {
            get {
                return ResourceManager.GetString("ShareCantShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: cannot share to a negative receiver ({0})!.
        /// </summary>
        public static string ShareNegativeReceiver {
            get {
                return ResourceManager.GetString("ShareNegativeReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmhhh... negative snippet ({0}): it can&apos;t be shared!.
        /// </summary>
        public static string ShareNegSnippetError {
            get {
                return ResourceManager.GetString("ShareNegSnippetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: User is not allowed to change this snippet {0}.
        /// </summary>
        public static string UserNotAllowedToChangeError {
            get {
                return ResourceManager.GetString("UserNotAllowedToChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No no: User is not allowed to see this snippet {0}.
        /// </summary>
        public static string UserNotAllowedToSeeError {
            get {
                return ResourceManager.GetString("UserNotAllowedToSeeError", resourceCulture);
            }
        }
    }
}
