//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastrucMsg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Generic3PartyHelper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generic3PartyHelper() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.Infrastructure.Generic3PartyHelper.Generic3PartyHelper", typeof(Generic3PartyHelper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems that {0} is sleeping now!! Please, retry in a while!.
        /// </summary>
        public static string CantContact3Party {
            get {
                return ResourceManager.GetString("CantContact3Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! An error occurred while creating your account; please retry in a while!.
        /// </summary>
        public static string CantCreateUser {
            get {
                return ResourceManager.GetString("CantCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Ooops! An error occurred while saving your picture taken from {0}; please retry in a while....
        /// </summary>
        public static string CantSavePicture {
            get {
                return ResourceManager.GetString("CantSavePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops! An error occurred while saving your profile: please retry in a while....
        /// </summary>
        public static string CantSaveProfile {
            get {
                return ResourceManager.GetString("CantSaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... An error occurred while validating your credentials: please, retry in a while!.
        /// </summary>
        public static string CantValidateCredentials {
            get {
                return ResourceManager.GetString("CantValidateCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge accomplished, but no changes occurred since all the information were already in place.
        /// </summary>
        public static string MergeWithNoChanges {
            get {
                return ResourceManager.GetString("MergeWithNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found the following users with the provided credentials; please choose one of them:.
        /// </summary>
        public static string SeveralUsersWithSameCredentials {
            get {
                return ResourceManager.GetString("SeveralUsersWithSameCredentials", resourceCulture);
            }
        }
    }
}
