//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerMsg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Access {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Access() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.ControllerMsg.Access.Access", typeof(Access).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmmhhh, are you sure about your credentials?.
        /// </summary>
        public static string LoginErrorMsg {
            get {
                return ResourceManager.GetString("LoginErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying your credentials, please wait....
        /// </summary>
        public static string LoginOneAllMsg {
            get {
                return ResourceManager.GetString("LoginOneAllMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops, we failed to generate a new password, please try again!.
        /// </summary>
        public static string RetrievePswCantGeneratePsw {
            get {
                return ResourceManager.GetString("RetrievePswCantGeneratePsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woah, it seems that this email does not exist in any account in Snip2Code! Check it please!.
        /// </summary>
        public static string RetrievePswNullUser {
            get {
                return ResourceManager.GetString("RetrievePswNullUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very good! Your temporary password has been sent to your email..
        /// </summary>
        public static string RetrievePswPswSent {
            get {
                return ResourceManager.GetString("RetrievePswPswSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woah, it seems that this account is not yet active!&lt;br/&gt;
        ///Please check your email now and follow the link printed there!.
        /// </summary>
        public static string RetrievePswUserNotActive {
            get {
                return ResourceManager.GetString("RetrievePswUserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, you must accept the terms of service....
        /// </summary>
        public static string SignupAcceptToS {
            get {
                return ResourceManager.GetString("SignupAcceptToS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops! Seems that someone already invited you to join Snip2Code!&lt;br/&gt;
        ///Please check your email now and follow the link printed there!.
        /// </summary>
        public static string SignupEmailAlreadyInvited {
            get {
                return ResourceManager.GetString("SignupEmailAlreadyInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, no! It seems that someone else already registered with this email!.
        /// </summary>
        public static string SignupEmailAlreadyPresent {
            get {
                return ResourceManager.GetString("SignupEmailAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops, an error occurred while creating your account... Please, try again!.
        /// </summary>
        public static string SignupGenericError {
            get {
                return ResourceManager.GetString("SignupGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, no... captcha input seems invalid: try again!.
        /// </summary>
        public static string SignupInvalidCaptcha {
            get {
                return ResourceManager.GetString("SignupInvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, no! It seems that someone else already registered with this username!.
        /// </summary>
        public static string SignupNicknameAlreadyPresent {
            get {
                return ResourceManager.GetString("SignupNicknameAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords don&apos;t match..
        /// </summary>
        public static string SignupPasswordMismatch {
            get {
                return ResourceManager.GetString("SignupPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short! At least 4 chars without spaces....
        /// </summary>
        public static string SignupPswWrongLenght {
            get {
                return ResourceManager.GetString("SignupPswWrongLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is taken, try.
        /// </summary>
        public static string SignupSuggestions {
            get {
                return ResourceManager.GetString("SignupSuggestions", resourceCulture);
            }
        }
    }
}
