//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NppPluginNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NppPluginNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Snip2Code.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap addSnip {
            get {
                object obj = ResourceManager.GetObject("addSnip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon addSnipIco {
            get {
                object obj = ResourceManager.GetObject("addSnipIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Snippet.
        /// </summary>
        public static string AddSnippetButton {
            get {
                return ResourceManager.GetString("AddSnippetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Snippet.
        /// </summary>
        public static string AddSnippetWindowTitle {
            get {
                return ResourceManager.GetString("AddSnippetWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window cannot be started. Please check product compatibility..
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap change {
            get {
                object obj = ResourceManager.GetObject("change", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeBtnText {
            get {
                return ResourceManager.GetString("ChangeBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap channel {
            get {
                object obj = ResourceManager.GetObject("channel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window and Login.
        /// </summary>
        public static string CloseWindowAndLoginBtn {
            get {
                return ResourceManager.GetString("CloseWindowAndLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseWindowButton {
            get {
                return ResourceManager.GetString("CloseWindowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler, log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;log4net&gt;
        ///    &lt;appender name=&quot;Console&quot; type=&quot;log4net.Appender.DebugAppender&quot;&gt;
        ///      &lt;layout type=&quot;log4net.Layout.PatternLayout&quot;&gt;
        ///        &lt;!-- Pattern to output the caller&apos;s file name and line number --&gt;
        ///        &lt;conversionPattern value=&quot;%5level (%file:%line) - %message%newline&quot; /&gt;
        ///      &lt;/layout&gt;
        ///    &lt;/ap [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfigContent {
            get {
                return ResourceManager.GetString("ConfigContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings.
        /// </summary>
        public static string ConnectionSettingsText {
            get {
                return ResourceManager.GetString("ConnectionSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your snippet here!
        ///i.e. a comment over a method and peculiar information needed to maximize the utility of this snippet in the future and for other people.
        /// </summary>
        public static string DescriptionTextBox {
            get {
                return ResourceManager.GetString("DescriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap emptyProfilePic_50x50 {
            get {
                object obj = ResourceManager.GetObject("emptyProfilePic 50x50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!! There was an error in the communication with the remote server. Please retry!.
        /// </summary>
        public static string ErrorCodes_COMMUNICATION_ERROR {
            get {
                return ResourceManager.GetString("ErrorCodes_COMMUNICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!! Something was wrong in the last operation. Please, retry!.
        /// </summary>
        public static string ErrorCodes_FAIL {
            get {
                return ResourceManager.GetString("ErrorCodes_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!! There was an error in the communication with the remote server. Please retry!.
        /// </summary>
        public static string ErrorCodes_INVALID_INPUT_FORMAT {
            get {
                return ResourceManager.GetString("ErrorCodes_INVALID_INPUT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmmh, seems you are not allowed to perform this operation. Check your permissions!.
        /// </summary>
        public static string ErrorCodes_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ErrorCodes_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!! Seems that you are not logged in. Please, login and retry!.
        /// </summary>
        public static string ErrorCodes_NOT_LOGGED_IN {
            get {
                return ResourceManager.GetString("ErrorCodes_NOT_LOGGED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string ErrorCodes_OK {
            get {
                return ResourceManager.GetString("ErrorCodes_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!! Seems that the target group has been deleted! Please, check with the group administrator and retry!.
        /// </summary>
        public static string ErrorCodes_TARGET_GROUP_DELETED {
            get {
                return ResourceManager.GetString("ErrorCodes_TARGET_GROUP_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! The remote server is taking too long to answer. Please retry in a while!.
        /// </summary>
        public static string ErrorCodes_TIMEOUT {
            get {
                return ResourceManager.GetString("ErrorCodes_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!! Something was wrong in the last action. Please, retry!.
        /// </summary>
        public static string ErrorCodes_UNKNOWN {
            get {
                return ResourceManager.GetString("ErrorCodes_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch!! Seems that some input value are not correct. Please, check the content and retry!.
        /// </summary>
        public static string ErrorCodes_WRONG_INPUT {
            get {
                return ResourceManager.GetString("ErrorCodes_WRONG_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred, please try again later..
        /// </summary>
        public static string GenericSnippetWSError {
            get {
                return ResourceManager.GetString("GenericSnippetWSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill-up the required fields..
        /// </summary>
        public static string IncompleteInput {
            get {
                return ResourceManager.GetString("IncompleteInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon infoIco {
            get {
                object obj = ResourceManager.GetObject("infoIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login detected:.
        /// </summary>
        public static string InvalidLoginMsg {
            get {
                return ResourceManager.GetString("InvalidLoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username / Password. Please check your credentials..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon loginIco {
            get {
                object obj = ResourceManager.GetObject("loginIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loginToolbar {
            get {
                object obj = ResourceManager.GetObject("loginToolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a short title to your snippet here!
        ///i.e. a method signature and where you will use it.
        /// </summary>
        public static string NameTextBox {
            get {
                return ResourceManager.GetString("NameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem connecting to the server. Please check your connection..
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one item.
        /// </summary>
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No snippets have been found..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PackageIco {
            get {
                object obj = ResourceManager.GetObject("PackageIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap publish {
            get {
                object obj = ResourceManager.GetObject("publish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string PublishButtonText {
            get {
                return ResourceManager.GetString("PublishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: some items may have not been updated properly. Please retry..
        /// </summary>
        public static string PublishErrorUnpublishing {
            get {
                return ResourceManager.GetString("PublishErrorUnpublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon publishIco {
            get {
                object obj = ResourceManager.GetObject("publishIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to follow a channel or create your own, in order to publish something.
        /// </summary>
        public static string PublishNoChannelFollowed {
            get {
                return ResourceManager.GetString("PublishNoChannelFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap publishSnippet {
            get {
                object obj = ResourceManager.GetObject("publishSnippet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Channel(s) where to publish the Snippet, so it will be visible to everyone!.
        /// </summary>
        public static string PublishSnippetTooltipFull {
            get {
                return ResourceManager.GetString("PublishSnippetTooltipFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Channel(s) where to publish the Snippet.
        /// </summary>
        public static string PublishSnippetTooltipSimple {
            get {
                return ResourceManager.GetString("PublishSnippetTooltipSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Snippet.
        /// </summary>
        public static string PublishSnippetWindowTitle {
            get {
                return ResourceManager.GetString("PublishSnippetWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap removeProperty {
            get {
                object obj = ResourceManager.GetObject("removeProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap saveSnippet {
            get {
                object obj = ResourceManager.GetObject("saveSnippet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_btn {
            get {
                object obj = ResourceManager.GetObject("search_btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon searchIco {
            get {
                object obj = ResourceManager.GetObject("searchIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search instead for:.
        /// </summary>
        public static string SearchMispellingText {
            get {
                return ResourceManager.GetString("SearchMispellingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} snippets.
        /// </summary>
        public static string SearchSnippetRecap1 {
            get {
                return ResourceManager.GetString("SearchSnippetRecap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to these are the first {0} ones.
        /// </summary>
        public static string SearchSnippetRecap2 {
            get {
                return ResourceManager.GetString("SearchSnippetRecap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Snippet.
        /// </summary>
        public static string SearchSnippetWindowTitle {
            get {
                return ResourceManager.GetString("SearchSnippetWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search.
        /// </summary>
        public static string SearchSuggestion {
            get {
                return ResourceManager.GetString("SearchSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server inserted is unreacheable now!.
        /// </summary>
        public static string ServerUnreacheableOrInvalid {
            get {
                return ResourceManager.GetString("ServerUnreacheableOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap share {
            get {
                object obj = ResourceManager.GetObject("share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Snip2Code_32x32 {
            get {
                object obj = ResourceManager.GetObject("Snip2Code 32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Snip2Code_40x240 {
            get {
                object obj = ResourceManager.GetObject("Snip2Code 40x240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Snip2Code16x16 {
            get {
                object obj = ResourceManager.GetObject("Snip2Code16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the Snippet in this frame.
        /// </summary>
        public static string SnippetTextBox {
            get {
                return ResourceManager.GetString("SnippetTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet text is invalid!.
        /// </summary>
        public static string SnippetWrongField_CODE {
            get {
                return ResourceManager.GetString("SnippetWrongField_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet is invalid and cannot be saved..
        /// </summary>
        public static string SnippetWrongField_default {
            get {
                return ResourceManager.GetString("SnippetWrongField_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid Description!.
        /// </summary>
        public static string SnippetWrongField_DESCR {
            get {
                return ResourceManager.GetString("SnippetWrongField_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid Title!.
        /// </summary>
        public static string SnippetWrongField_NAME {
            get {
                return ResourceManager.GetString("SnippetWrongField_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid property!.
        /// </summary>
        public static string SnippetWrongField_PROPERTIES {
            get {
                return ResourceManager.GetString("SnippetWrongField_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap spacerAddSnippet {
            get {
                object obj = ResourceManager.GetObject("spacerAddSnippet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap star_bmp {
            get {
                object obj = ResourceManager.GetObject("star_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert some tags, split by space (like: c# singleton pattern).
        /// </summary>
        public static string TagsTextBox {
            get {
                return ResourceManager.GetString("TagsTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateBtnText {
            get {
                return ResourceManager.GetString("UpdateBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserWindowTitle {
            get {
                return ResourceManager.GetString("UserWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Snippet.
        /// </summary>
        public static string ViewSnippetWindowTitle {
            get {
                return ResourceManager.GetString("ViewSnippetWindowTitle", resourceCulture);
            }
        }
    }
}
