//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Toolbar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Toolbar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.WebPages.Toolbar.Toolbar", typeof(Toolbar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss your changes.
        /// </summary>
        public static string CancelTooltip {
            get {
                return ResourceManager.GetString("CancelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyBtn {
            get {
                return ResourceManager.GetString("CopyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Snippet ( you cannot undo this operation ).
        /// </summary>
        public static string DeleteTooltip {
            get {
                return ResourceManager.GetString("DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this Snippet.
        /// </summary>
        public static string EditTooltip {
            get {
                return ResourceManager.GetString("EditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string MoveBtn {
            get {
                return ResourceManager.GetString("MoveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this Snippet with another Group.
        /// </summary>
        public static string MoveBtnTooltip {
            get {
                return ResourceManager.GetString("MoveBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewSnippetBtn {
            get {
                return ResourceManager.GetString("NewSnippetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Snippet.
        /// </summary>
        public static string NewSnippetTooltip {
            get {
                return ResourceManager.GetString("NewSnippetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string PublishBtn {
            get {
                return ResourceManager.GetString("PublishBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post this Snippet to a Public Channel.
        /// </summary>
        public static string PublishTooltip {
            get {
                return ResourceManager.GetString("PublishTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your edits for this Snippet.
        /// </summary>
        public static string SaveTooltip {
            get {
                return ResourceManager.GetString("SaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareBtn {
            get {
                return ResourceManager.GetString("ShareBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this Snippet with a Group of people.
        /// </summary>
        public static string ShareTooltip {
            get {
                return ResourceManager.GetString("ShareTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish.
        /// </summary>
        public static string UnPublishBtn {
            get {
                return ResourceManager.GetString("UnPublishBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Snippet from all published Channels and remove it from the Public space.
        /// </summary>
        public static string UnPublishTooltip {
            get {
                return ResourceManager.GetString("UnPublishTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unshare.
        /// </summary>
        public static string UnShareBtn {
            get {
                return ResourceManager.GetString("UnShareBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this Snippet from a Group.
        /// </summary>
        public static string UnShareTooltip {
            get {
                return ResourceManager.GetString("UnShareTooltip", resourceCulture);
            }
        }
    }
}
