//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutUs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.WebPages.AboutUs.AboutUs", typeof(AboutUs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect.
        /// </summary>
        public static string Collect {
            get {
                return ResourceManager.GetString("Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every software guru knows that a huge percentage of an application is made by simple chunks of code used in a bunch of other situations; such code snippets usually are part of the invaluable stock of knowledge of software experts, who re-use them in several different scenarios..
        /// </summary>
        public static string Content1 {
            get {
                return ResourceManager.GetString("Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a service that lets the user.
        /// </summary>
        public static string Content2 {
            get {
                return ResourceManager.GetString("Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string Content2And {
            get {
                return ResourceManager.GetString("Content2And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the code snippets used every day in the software application developing activities..
        /// </summary>
        public static string Content2bis {
            get {
                return ResourceManager.GetString("Content2bis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user decides whether each of his snippets is to be kept private in his own repository, may be shared with other colleagues and friends, or should be published to make them visible all over the world..
        /// </summary>
        public static string Content3 {
            get {
                return ResourceManager.GetString("Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These three different use cases may be applied for different user bases..
        /// </summary>
        public static string Content4 {
            get {
                return ResourceManager.GetString("Content4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capability to share such snippets, and to let other users comment and vote them, allow the user to continuously refine and optimize his snippets in an endless improving loop..
        /// </summary>
        public static string Content5 {
            get {
                return ResourceManager.GetString("Content5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private scenario may apply for single users who wants to store their code fragments in order to have them ready to use everywhere and with every device..
        /// </summary>
        public static string ContentLiPriv {
            get {
                return ResourceManager.GetString("ContentLiPriv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protected scenario applies most of all for software enterprises and open-source foundations, which need a tool to collect and make available their own guide-lines and common basic modules to develop software inside the organization in an efficient and cooperative way..
        /// </summary>
        public static string ContentLiProt {
            get {
                return ResourceManager.GetString("ContentLiProt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public scenario arises when users want to publish their snippets to make them visible to the rest of the world. Such users accumulate a bunch of points, running for the election of World Snip2Code Guru award..
        /// </summary>
        public static string ContentLiPub {
            get {
                return ResourceManager.GetString("ContentLiPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip2Code Mantra.
        /// </summary>
        public static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip2Code.
        /// </summary>
        public static string Snip2Code {
            get {
                return ResourceManager.GetString("Snip2Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
