//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Downloads {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Downloads() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.WebPages.Downloads.Downloads", typeof(Downloads).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are quite ready to expose our set of APIs, so that you will be able to define your own app!! If you are interested, please .
        /// </summary>
        public static string APIContent {
            get {
                return ResourceManager.GetString("APIContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public APIs.
        /// </summary>
        public static string APITitle {
            get {
                return ResourceManager.GetString("APITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:(function(e,a,g,h,f,c,b,d){if(!(f=e.jQuery)||g&gt;f.fn.jquery||h(f)){c=a.createElement(&quot;script&quot;);c.type=&quot;text/javascript&quot;;c.src=&quot;http://ajax.googleapis.com/ajax/libs/jquery/&quot;+g+&quot;/jquery.min.js&quot;;c.onload=c.onreadystatechange=function(){if(!b&amp;&amp;(!(d=this.readyState)||d==&quot;loaded&quot;||d==&quot;complete&quot;)){h((f=e.jQuery).noConflict(1),b=1);f(c).remove()}};a.documentElement.childNodes[0].appendChild(c)}})(window,document,&quot;1.6.1&quot;,function($,L){var%20jsStr=&quot;&lt;script%20type=&apos;text/javascript&apos;%20src=&apos;^^^BrowserPlugin/s2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BookmarkletContent {
            get {
                return ResourceManager.GetString("BookmarkletContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Snip2Code Bookmarklet for your Browser.
        /// </summary>
        public static string BookmarkletTitle {
            get {
                return ResourceManager.GetString("BookmarkletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us!.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip2Code Extensions and Plug-Ins.
        /// </summary>
        public static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Eclipse development environment.
        /// </summary>
        public static string Eclipse {
            get {
                return ResourceManager.GetString("Eclipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using.
        /// </summary>
        public static string EclipseContent1 {
            get {
                return ResourceManager.GetString("EclipseContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Snip2Code Plug-In for Eclipse.
        /// </summary>
        public static string EclipseTitle {
            get {
                return ResourceManager.GetString("EclipseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Git Utility.
        /// </summary>
        public static string GitClientTitle {
            get {
                return ResourceManager.GetString("GitClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Snip2Code Plug-In for IntelliJ IDEA.
        /// </summary>
        public static string IntelliJTitle {
            get {
                return ResourceManager.GetString("IntelliJTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Snip2Code App for Mac OS X.
        /// </summary>
        public static string MacTitle {
            get {
                return ResourceManager.GetString("MacTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Snip2Code Plug-In for Notepad++.
        /// </summary>
        public static string NotepadppTitle {
            get {
                return ResourceManager.GetString("NotepadppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VSContent {
            get {
                return ResourceManager.GetString("VSContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Snip2Code Extension for Visual Studio.
        /// </summary>
        public static string VSTitle {
            get {
                return ResourceManager.GetString("VSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Snip2Code HTML Widget.
        /// </summary>
        public static string WidgetTitle {
            get {
                return ResourceManager.GetString("WidgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Snip2Code Windows8 App.
        /// </summary>
        public static string Win8Title {
            get {
                return ResourceManager.GetString("Win8Title", resourceCulture);
            }
        }
    }
}
