//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.WebModels.UserInfo.UserInfo", typeof(UserInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field required (only spaces isn&apos;t fair!).
        /// </summary>
        public static string BlankField {
            get {
                return ResourceManager.GetString("BlankField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this not a valid email!.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know your beautiful name! (2 to 30 chars).
        /// </summary>
        public static string FirstNameLength {
            get {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know your awesome last name! (2 to 30 chars).
        /// </summary>
        public static string LastNameLength {
            get {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a little password: 4 to 20 chars required.
        /// </summary>
        public static string PswLength {
            get {
                return ResourceManager.GetString("PswLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check passwords: they must be the same!.
        /// </summary>
        public static string PswMatch {
            get {
                return ResourceManager.GetString("PswMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, accept the terms!.
        /// </summary>
        public static string TosAccept {
            get {
                return ResourceManager.GetString("TosAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 to 30 chars required.
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your unique nickname: white spaces and other special characters are not cool!  (3 to 50 chars).
        /// </summary>
        public static string UserNameRegex {
            get {
                return ResourceManager.GetString("UserNameRegex", resourceCulture);
            }
        }
    }
}
