//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerMsg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Editor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Editor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snip2Code.Resources.ControllerMsg.Editor.Editor", typeof(Editor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch! We haven&apos;t been able to delete this snippet.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch! We haven&apos;t been able to find this snippet.
        /// </summary>
        public static string EditError {
            get {
                return ResourceManager.GetString("EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch! The group that would own this snippet has been removed. Try with another group..
        /// </summary>
        public static string GroupDeletedWhileCreating {
            get {
                return ResourceManager.GetString("GroupDeletedWhileCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch! The group that would own this snippet has been removed. The ownership of this snippet has returned to its creator..
        /// </summary>
        public static string GroupDeletedWhileEditing {
            get {
                return ResourceManager.GetString("GroupDeletedWhileEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmhhh... Seems that you haven&apos;t got the rights to edit this snippet..
        /// </summary>
        public static string NotAllowedError {
            get {
                return ResourceManager.GetString("NotAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something wrong during snippet save... Please retry in a while!.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acch! Seems that you are no more allowed to edit this snippet. Check your permissions together with the administrators of the group!.
        /// </summary>
        public static string SaveErrorNotAllowed {
            get {
                return ResourceManager.GetString("SaveErrorNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmhhh... Seems that the Code field is not valid.
        /// </summary>
        public static string SaveErrorWrongCode {
            get {
                return ResourceManager.GetString("SaveErrorWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmhhh... Seems that the Description field is not valid.
        /// </summary>
        public static string SaveErrorWrongDescr {
            get {
                return ResourceManager.GetString("SaveErrorWrongDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmhhh... Seems that the Title field is not valid.
        /// </summary>
        public static string SaveErrorWrongName {
            get {
                return ResourceManager.GetString("SaveErrorWrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmhhh... Seems that the Price per View field is not valid.
        /// </summary>
        public static string SaveErrorWrongPrice {
            get {
                return ResourceManager.GetString("SaveErrorWrongPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmhhh... Seems that one of the Properties is not valid.
        /// </summary>
        public static string SaveErrorWrongProperties {
            get {
                return ResourceManager.GetString("SaveErrorWrongProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not logged in.
        /// </summary>
        public static string UserNotLogged {
            get {
                return ResourceManager.GetString("UserNotLogged", resourceCulture);
            }
        }
    }
}
